spring:
  application:
    name: eureka-server1 # 应用名
server:
  port: 8180 # 端口
eureka:
  instance:
    hostname: localhost # 域名
  client:
    service-url:
      defaultZone: http://localhost:8184/eureka # 其他注册中心的地址
#    fetch-registry: false # 是否开启搜索服务，Server不提供服务，故应关闭
#    register-with-eureka: false # 注册自己，Server不需注册自己，故应关闭
